kind: PersistentVolume
apiVersion: v1
metadata:
  name: kafka-broker-$ITEM
  labels:
    type: local
spec:
  storageClassName: kafka-broker
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/kafka"