kind: Service
apiVersion: v1
metadata:
  name: kafka-manager
  namespace: kafka
spec:
  selector:
    app: kafka-manager
  type: NodePort    
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
